### ISSUE TITLE
In this example, the output should be 53 Steve, 54 Steve, 55 Steve. But actually, you were written 53 Steve, 53 Steve, 53 Steve in the explanation.

### ISSUE THREAD

**Issue by praneethbairy** [Jasbir96/full_stack_notes#3]
var firstName = "Loki"
let cap = {
    firstName : "Steve",
    sayHi : function(){
        console.log("53", this.firstName);
        const subInner = () => {
            console.log("54", this.firstName);
            const iAmInner = ()=> {
                console.log("55", this.firstName);
            }
            iAmInner(); 55 Steve
        }
        subInner();  // will console 54 Steve
    }
}
cap.sayHi();    // will console 53 Steve

firstly, cap.sayHi() will call, then as it a method call then the value of this will be the object of cap, so it will be of value Steve.

next, iAmInner() will call, as it is a function call with Arrow function, as Arrow function will not have this, they will look for outer scope (i.e., sayHi()) so it will be value of Steve. lly, for subInner() it is same as iAmInner().

**Comment by Jasbir96** [comment]
yes you are  it will be steve all the way

**Comment by Jasbir96** [comment]
correct
